REGION_CONVERT_KEYS = {
    "Cemetery of Ash": "CA",
    "Firelink Shrine": "FS",
    "High Wall of Lothric": "HWL",
    "Greirat's Shop": "GrShop",
    "Undead Settlement": "US",
    "Road of Sacrifices": "RS",
    "Farron Keep": "FK",
    "Cathedral of the Deep": "CD",
    "Catacombs of Carthus": "CC",
    "Smouldering Lake": "SL",
    "Irithyll of the Boreal Valley": "IBV",
    "Irithyll Dungeon": "ID",
    "Karla's Shop": "KarlaShop",
    "Painted World of Ariandel (Before Contraption)": "PW1",
    "Anor Londo": "AL",
    "Profaned Capital": "PC",
    "Painted World of Ariandel (After Contraption)": "PW2",
    "Lothric Castle": "LC",
    "Consumed King's Garden": "CKG",
    "Untended Graves": "UG",
    "Firelink Shrine Bell Tower": "FSBT",
    "Grand Archives": "GA",
    "Archdragon Peak (Through Fort)": "AP1",
    "Archdragon Peak (After Fort)": "AP2",
    "Kiln of the First Flame": "KFF",
    "Dreg Heap": "DH",
    "Ringed City": "RC",
}
