VISIBILITY_CONVERT_KEYS = {
    "Everywhere": "everywhere",

    "Cemetery of Ash": "ca",
    "Firelink Shrine": "fs",
    "Firelink Shrine Bell Tower": "fsbt",
    "High Wall of Lothric": "hwl",
    "Undead Settlement": "us",
    "Road of Sacrifices": "rs",
    "Cathedral of the Deep": "cd",
    "Farron Keep": "fk",
    "Catacombs of Carthus": "cc",
    "Smouldering Lake": "sl",
    "Irithyll of the Boreal Valley": "ibv",
    "Irithyll Dungeon": "id",
    "Profaned Capital": "pc",
    "Anor Londo": "al",
    "Lothric Castle": "lc",
    "Consumed King's Garden": "ckg",
    "Grand Archives": "ga",
    "Untended Graves": "ug",
    "Archdragon Peak": "ap",
    "Painted World of Ariandel": "pwa",
    "Dreg Heap": "dh",
    "Ringed City": "rc",
    "Kiln of the First Flame": "kff",

    "Missable": "missable",
    "DLC": "dlc",
    "New Game+": "ng+",
    
    "Prominent": "prominent",
    "Progression": "progression",
    "Boss Rewards": "bossReward",
    "Miniboss Rewards": "minibossReward",
    "Mimic Rewards": "mimicReward",
    "Hostile NPC Rewards": "hostileNPCReward",
    "Friendly NPC Rewards": "friendlyNPCReward",
    "Small Crystal Lizards": "smallCrystalLizard",
    "Drops": "drop",
    "Shops": "fromShop",
    "Upgrade": "weaponUpgrade",
    "Small Souls": "smallSoul",
    "Boss Souls": "bossSoul",
    "Unique": "unique",
    "Healing": "healingUpgrade",
    "Miscellaneous": "misc",
    "Hidden": "hidden",
    "Weapons": "weapon",
    "Shields": "shield",
    "Armor": "armor",
    "Rings": "ring",
    "Spells": "spell",
}
